#pragma once
namespace GameLogic
{

struct ArrowLauncher;
struct ARZSetup;
struct BreakoffPillar;
struct ChopChop;
struct Grounder;
struct Wisp;
struct BonusTitleCard;
struct CircleBumper;
struct CNZSetup;
struct CNZSpotlight;
struct ConveyorBelt;
struct Crawl;
struct Flipper;
struct Plunger;
struct SlotDisplay;
struct SlotMachine;
struct SlotPrize;
struct SnakeBlock;
struct TargetBumper;
struct TriBumper;
struct VFlipper;
struct BGSwitch;
struct BreakableWall;
struct Button;
struct CollapsingPlatform;
struct Decoration;
struct FallTrigger;
struct FlingRamp;
struct ForceSpin;
struct ForceUnstick;
struct GenericTrigger;
struct ParallaxSprite;
struct Platform;
struct PlatformControl;
struct PlatformNode;
struct ScreenWrap;
struct SpinBooster;
struct Springboard;
struct TilePlatform;
struct Water;
struct ChemicalBall;
struct ChemicalDropper;
struct CPZEggman;
struct CPZSetup;
struct Grabber;
struct OneWayDoor;
struct RotatingStair;
struct SpeedBooster;
struct Spiny;
struct Staircase;
struct TippingPlatform;
struct TransportTube;
struct TubeSpring;
struct Blastoid;
struct Crate;
struct DEZSetup;
struct FlasherMKII;
struct JacobsLadder;
struct MetalArm;
struct PopOut;
struct Press;
struct Tubinaut;
struct Bridge;
struct BurningLog;
struct Buzzer;
struct Coconuts;
struct CorkscrewPath;
struct EggDriller;
struct EHZEggman;
struct EHZSetup;
struct Masher;
struct ActClear;
struct Animals;
struct Announcer;
struct BoundsMarker;
struct Camera;
struct COverlay;
struct Debris;
struct DebugMode;
struct Dust;
struct EggPrison;
struct Explosion;
struct GameOver;
struct HUD;
struct ImageTrail;
struct InvincibleStars;
struct InvisibleBlock;
struct ItemBox;
struct Localization;
struct Music;
struct PauseMenu;
struct PlaneSwitch;
struct Player;
struct ReplayRecorder;
struct Ring;
struct RPUpdate;
struct SaveGame;
struct ScoreBonus;
struct Shield;
struct SignPost;
struct SpecialRing;
struct Spikes;
struct Spring;
struct StarPost;
struct SuperFlicky;
struct SuperSparkle;
struct TimeAttackGate;
struct TitleCard;
struct Zone;
struct BadnikHelpers;
struct CutsceneRules;
struct CutsceneSeq;
struct DialogRunner;
struct DrawHelpers;
struct FXAniTiles;
struct FXAudioPan;
struct FXFade;
struct FXTileModifier;
struct GameProgress;
struct LogHelpers;
struct MathHelpers;
struct MenuParam;
struct Options;
struct PlayerHelpers;
struct PlayerProbe;
struct ReplayDB;
struct RPCHelpers;
struct Soundboard;
struct TimeAttackData;
struct Batbot;
struct HPZSetup;
struct Jellygnite;
struct Pendulum;
struct RailRocket;
struct Redz;
struct Stegway;
struct WaterGush;
struct AIZRockPile;
struct HTZSetup;
struct Rexon;
struct RisingLava;
struct SeeSaw;
struct Sol;
struct Spiker;
struct ZipLine;
struct ContinuePlayer;
struct ContinueSetup;
struct DAControl;
struct DASetup;
struct ExtrasMenu;
struct LevelSelect;
struct MainMenu;
struct ManiaModeMenu;
struct MenuSetup;
struct OptionsMenu;
struct SaveMenu;
struct SaveMenuIconBG;
struct TAMenuIconBG;
struct ThanksSetup;
struct TimeAttackMenu;
struct UIButton;
struct UIButtonLabel;
struct UIButtonPrompt;
struct UICarousel;
struct UICharButton;
struct UIChoice;
struct UIControl;
struct UIDialog;
struct UIDiorama;
struct UIInfoLabel;
struct UIKeyBinder;
struct UILoadingIcon;
struct UIOptionPanel;
struct UIPicture;
struct UIPopover;
struct UIRankButton;
struct UIReplayCarousel;
struct UIResPicker;
struct UISaveSlot;
struct UIShifter;
struct UISlider;
struct UISubHeading;
struct UITABanner;
struct UITAZoneModule;
struct UIText;
struct UITransition;
struct UIVideo;
struct UIWidgets;
struct UIWinSize;
struct Aquis;
struct BallCannon;
struct Fan;
struct GasPlatform;
struct Octus;
struct OOZSetup;
struct PushSpring;
struct SCZSetup;
struct Tornado;
struct TornadoPath;
struct HP_Background;
struct HP_Checkpoint;
struct HP_Collectable;
struct HP_Halfpipe;
struct HP_HUD;
struct HP_Message;
struct HP_Player;
struct HP_Setup;
struct HP_SpecialClear;
struct Bomb;
struct Caterkiller;
struct Pinata;
struct RollerMKII;
struct SeltzerBottle;
struct SeltzerWater;
struct SinkTrash;
struct SSZSetup;
struct Vultron;
struct BouncePlant;
struct Dragonfly;
struct GymBar;
struct PetalPile;
struct Rhinobot;
struct Snowflakes;
struct Splats;
struct SWZSetup;
struct UncurlPlant;
struct WallBumper;
struct TestObject;
struct LogoSetup;
struct Sega;
struct TitleLogo;
struct TitleSetup;
struct TitleSonic;
struct Twinkle;

} // namespace GameLogic

#include "Objects/ARZ/ArrowLauncher.hpp"
#include "Objects/ARZ/ARZSetup.hpp"
#include "Objects/ARZ/BreakoffPillar.hpp"
#include "Objects/ARZ/ChopChop.hpp"
#include "Objects/ARZ/Grounder.hpp"
#include "Objects/ARZ/Wisp.hpp"
#include "Objects/Bonus/BonusTitleCard.hpp"
#include "Objects/CNZ/CircleBumper.hpp"
#include "Objects/CNZ/CNZSetup.hpp"
#include "Objects/CNZ/CNZSpotlight.hpp"
#include "Objects/CNZ/ConveyorBelt.hpp"
#include "Objects/CNZ/Crawl.hpp"
#include "Objects/CNZ/Flipper.hpp"
#include "Objects/CNZ/Plunger.hpp"
#include "Objects/CNZ/SlotDisplay.hpp"
#include "Objects/CNZ/SlotMachine.hpp"
#include "Objects/CNZ/SlotPrize.hpp"
#include "Objects/CNZ/SnakeBlock.hpp"
#include "Objects/CNZ/TargetBumper.hpp"
#include "Objects/CNZ/TriBumper.hpp"
#include "Objects/CNZ/VFlipper.hpp"
#include "Objects/Common/BGSwitch.hpp"
#include "Objects/Common/BreakableWall.hpp"
#include "Objects/Common/Button.hpp"
#include "Objects/Common/CollapsingPlatform.hpp"
#include "Objects/Common/Decoration.hpp"
#include "Objects/Common/FallTrigger.hpp"
#include "Objects/Common/FlingRamp.hpp"
#include "Objects/Common/ForceSpin.hpp"
#include "Objects/Common/ForceUnstick.hpp"
#include "Objects/Common/GenericTrigger.hpp"
#include "Objects/Common/ParallaxSprite.hpp"
#include "Objects/Common/Platform.hpp"
#include "Objects/Common/PlatformControl.hpp"
#include "Objects/Common/PlatformNode.hpp"
#include "Objects/Common/ScreenWrap.hpp"
#include "Objects/Common/SpinBooster.hpp"
#include "Objects/Common/Springboard.hpp"
#include "Objects/Common/TilePlatform.hpp"
#include "Objects/Common/Water.hpp"
#include "Objects/CPZ/ChemicalBall.hpp"
#include "Objects/CPZ/ChemicalDropper.hpp"
#include "Objects/CPZ/CPZEggman.hpp"
#include "Objects/CPZ/CPZSetup.hpp"
#include "Objects/CPZ/Grabber.hpp"
#include "Objects/CPZ/OneWayDoor.hpp"
#include "Objects/CPZ/RotatingStair.hpp"
#include "Objects/CPZ/SpeedBooster.hpp"
#include "Objects/CPZ/Spiny.hpp"
#include "Objects/CPZ/Staircase.hpp"
#include "Objects/CPZ/TippingPlatform.hpp"
#include "Objects/CPZ/TransportTube.hpp"
#include "Objects/CPZ/TubeSpring.hpp"
#include "Objects/DEZ/Blastoid.hpp"
#include "Objects/DEZ/Crate.hpp"
#include "Objects/DEZ/DEZSetup.hpp"
#include "Objects/DEZ/FlasherMKII.hpp"
#include "Objects/DEZ/JacobsLadder.hpp"
#include "Objects/DEZ/MetalArm.hpp"
#include "Objects/DEZ/PopOut.hpp"
#include "Objects/DEZ/Press.hpp"
#include "Objects/DEZ/Tubinaut.hpp"
#include "Objects/EHZ/Bridge.hpp"
#include "Objects/EHZ/BurningLog.hpp"
#include "Objects/EHZ/Buzzer.hpp"
#include "Objects/EHZ/Coconuts.hpp"
#include "Objects/EHZ/CorkscrewPath.hpp"
#include "Objects/EHZ/EggDriller.hpp"
#include "Objects/EHZ/EHZEggman.hpp"
#include "Objects/EHZ/EHZSetup.hpp"
#include "Objects/EHZ/Masher.hpp"
#include "Objects/Global/ActClear.hpp"
#include "Objects/Global/Animals.hpp"
#include "Objects/Global/Announcer.hpp"
#include "Objects/Global/BoundsMarker.hpp"
#include "Objects/Global/Camera.hpp"
#include "Objects/Global/COverlay.hpp"
#include "Objects/Global/Debris.hpp"
#include "Objects/Global/DebugMode.hpp"
#include "Objects/Global/Dust.hpp"
#include "Objects/Global/EggPrison.hpp"
#include "Objects/Global/Explosion.hpp"
#include "Objects/Global/GameOver.hpp"
#include "Objects/Global/HUD.hpp"
#include "Objects/Global/ImageTrail.hpp"
#include "Objects/Global/InvincibleStars.hpp"
#include "Objects/Global/InvisibleBlock.hpp"
#include "Objects/Global/ItemBox.hpp"
#include "Objects/Global/Localization.hpp"
#include "Objects/Global/Music.hpp"
#include "Objects/Global/PauseMenu.hpp"
#include "Objects/Global/PlaneSwitch.hpp"
#include "Objects/Global/Player.hpp"
#include "Objects/Global/ReplayRecorder.hpp"
#include "Objects/Global/Ring.hpp"
#include "Objects/Global/RPUpdate.hpp"
#include "Objects/Global/SaveGame.hpp"
#include "Objects/Global/ScoreBonus.hpp"
#include "Objects/Global/Shield.hpp"
#include "Objects/Global/SignPost.hpp"
#include "Objects/Global/SpecialRing.hpp"
#include "Objects/Global/Spikes.hpp"
#include "Objects/Global/Spring.hpp"
#include "Objects/Global/StarPost.hpp"
#include "Objects/Global/SuperFlicky.hpp"
#include "Objects/Global/SuperSparkle.hpp"
#include "Objects/Global/TimeAttackGate.hpp"
#include "Objects/Global/TitleCard.hpp"
#include "Objects/Global/Zone.hpp"
#include "Objects/Helpers/BadnikHelpers.hpp"
#include "Objects/Helpers/CutsceneRules.hpp"
#include "Objects/Helpers/CutsceneSeq.hpp"
#include "Objects/Helpers/DialogRunner.hpp"
#include "Objects/Helpers/DrawHelpers.hpp"
#include "Objects/Helpers/FXAniTiles.hpp"
#include "Objects/Helpers/FXAudioPan.hpp"
#include "Objects/Helpers/FXFade.hpp"
#include "Objects/Helpers/FXTileModifier.hpp"
#include "Objects/Helpers/GameProgress.hpp"
#include "Objects/Helpers/LogHelpers.hpp"
#include "Objects/Helpers/MathHelpers.hpp"
#include "Objects/Helpers/MenuParam.hpp"
#include "Objects/Helpers/Options.hpp"
#include "Objects/Helpers/PlayerHelpers.hpp"
#include "Objects/Helpers/PlayerProbe.hpp"
#include "Objects/Helpers/ReplayDB.hpp"
#include "Objects/Helpers/RPCHelpers.hpp"
#include "Objects/Helpers/Soundboard.hpp"
#include "Objects/Helpers/TimeAttackData.hpp"
#include "Objects/HPZ/Batbot.hpp"
#include "Objects/HPZ/HPZSetup.hpp"
#include "Objects/HPZ/Jellygnite.hpp"
#include "Objects/HPZ/Pendulum.hpp"
#include "Objects/HPZ/RailRocket.hpp"
#include "Objects/HPZ/Redz.hpp"
#include "Objects/HPZ/Stegway.hpp"
#include "Objects/HPZ/WaterGush.hpp"
#include "Objects/HTZ/AIZRockPile.hpp"
#include "Objects/HTZ/HTZSetup.hpp"
#include "Objects/HTZ/Rexon.hpp"
#include "Objects/HTZ/RisingLava.hpp"
#include "Objects/HTZ/SeeSaw.hpp"
#include "Objects/HTZ/Sol.hpp"
#include "Objects/HTZ/Spiker.hpp"
#include "Objects/HTZ/ZipLine.hpp"
#include "Objects/Menu/ContinuePlayer.hpp"
#include "Objects/Menu/ContinueSetup.hpp"
#include "Objects/Menu/DAControl.hpp"
#include "Objects/Menu/DASetup.hpp"
#include "Objects/Menu/ExtrasMenu.hpp"
#include "Objects/Menu/LevelSelect.hpp"
#include "Objects/Menu/MainMenu.hpp"
#include "Objects/Menu/ManiaModeMenu.hpp"
#include "Objects/Menu/MenuSetup.hpp"
#include "Objects/Menu/OptionsMenu.hpp"
#include "Objects/Menu/SaveMenu.hpp"
#include "Objects/Menu/SaveMenuIconBG.hpp"
#include "Objects/Menu/TAMenuIconBG.hpp"
#include "Objects/Menu/ThanksSetup.hpp"
#include "Objects/Menu/TimeAttackMenu.hpp"
#include "Objects/Menu/UIButton.hpp"
#include "Objects/Menu/UIButtonLabel.hpp"
#include "Objects/Menu/UIButtonPrompt.hpp"
#include "Objects/Menu/UICarousel.hpp"
#include "Objects/Menu/UICharButton.hpp"
#include "Objects/Menu/UIChoice.hpp"
#include "Objects/Menu/UIControl.hpp"
#include "Objects/Menu/UIDialog.hpp"
#include "Objects/Menu/UIDiorama.hpp"
#include "Objects/Menu/UIInfoLabel.hpp"
#include "Objects/Menu/UIKeyBinder.hpp"
#include "Objects/Menu/UILoadingIcon.hpp"
#include "Objects/Menu/UIOptionPanel.hpp"
#include "Objects/Menu/UIPicture.hpp"
#include "Objects/Menu/UIPopover.hpp"
#include "Objects/Menu/UIRankButton.hpp"
#include "Objects/Menu/UIReplayCarousel.hpp"
#include "Objects/Menu/UIResPicker.hpp"
#include "Objects/Menu/UISaveSlot.hpp"
#include "Objects/Menu/UIShifter.hpp"
#include "Objects/Menu/UISlider.hpp"
#include "Objects/Menu/UISubHeading.hpp"
#include "Objects/Menu/UITABanner.hpp"
#include "Objects/Menu/UITAZoneModule.hpp"
#include "Objects/Menu/UIText.hpp"
#include "Objects/Menu/UITransition.hpp"
#include "Objects/Menu/UIVideo.hpp"
#include "Objects/Menu/UIWidgets.hpp"
#include "Objects/Menu/UIWinSize.hpp"
#include "Objects/OOZ/Aquis.hpp"
#include "Objects/OOZ/BallCannon.hpp"
#include "Objects/OOZ/Fan.hpp"
#include "Objects/OOZ/GasPlatform.hpp"
#include "Objects/OOZ/Octus.hpp"
#include "Objects/OOZ/OOZSetup.hpp"
#include "Objects/OOZ/PushSpring.hpp"
#include "Objects/SFZ/SCZSetup.hpp"
#include "Objects/SFZ/Tornado.hpp"
#include "Objects/SFZ/TornadoPath.hpp"
#include "Objects/Special/HP_Background.hpp"
#include "Objects/Special/HP_Checkpoint.hpp"
#include "Objects/Special/HP_Collectable.hpp"
#include "Objects/Special/HP_Halfpipe.hpp"
#include "Objects/Special/HP_HUD.hpp"
#include "Objects/Special/HP_Message.hpp"
#include "Objects/Special/HP_Player.hpp"
#include "Objects/Special/HP_Setup.hpp"
#include "Objects/Special/HP_SpecialClear.hpp"
#include "Objects/SSZ/Bomb.hpp"
#include "Objects/SSZ/Caterkiller.hpp"
#include "Objects/SSZ/Pinata.hpp"
#include "Objects/SSZ/RollerMKII.hpp"
#include "Objects/SSZ/SeltzerBottle.hpp"
#include "Objects/SSZ/SeltzerWater.hpp"
#include "Objects/SSZ/SinkTrash.hpp"
#include "Objects/SSZ/SSZSetup.hpp"
#include "Objects/SSZ/Vultron.hpp"
#include "Objects/SWZ/BouncePlant.hpp"
#include "Objects/SWZ/Dragonfly.hpp"
#include "Objects/SWZ/GymBar.hpp"
#include "Objects/SWZ/PetalPile.hpp"
#include "Objects/SWZ/Rhinobot.hpp"
#include "Objects/SWZ/Snowflakes.hpp"
#include "Objects/SWZ/Splats.hpp"
#include "Objects/SWZ/SWZSetup.hpp"
#include "Objects/SWZ/UncurlPlant.hpp"
#include "Objects/SWZ/WallBumper.hpp"
#include "Objects/Test/TestObject.hpp"
#include "Objects/Title/LogoSetup.hpp"
#include "Objects/Title/Sega.hpp"
#include "Objects/Title/TitleLogo.hpp"
#include "Objects/Title/TitleSetup.hpp"
#include "Objects/Title/TitleSonic.hpp"
#include "Objects/Title/Twinkle.hpp"
