set(GENERATED_SOURCES
	src/S2M/Objects/ARZ/ArrowLauncher.cpp
	src/S2M/Objects/ARZ/ARZSetup.cpp
	src/S2M/Objects/ARZ/BreakoffPillar.cpp
	src/S2M/Objects/ARZ/ChopChop.cpp
	src/S2M/Objects/ARZ/Grounder.cpp
	src/S2M/Objects/ARZ/Wisp.cpp
	src/S2M/Objects/Bonus/BonusTitleCard.cpp
	src/S2M/Objects/CNZ/CircleBumper.cpp
	src/S2M/Objects/CNZ/CNZSetup.cpp
	src/S2M/Objects/CNZ/CNZSpotlight.cpp
	src/S2M/Objects/CNZ/ConveyorBelt.cpp
	src/S2M/Objects/CNZ/Crawl.cpp
	src/S2M/Objects/CNZ/Flipper.cpp
	src/S2M/Objects/CNZ/Plunger.cpp
	src/S2M/Objects/CNZ/SlotDisplay.cpp
	src/S2M/Objects/CNZ/SlotMachine.cpp
	src/S2M/Objects/CNZ/SlotPrize.cpp
	src/S2M/Objects/CNZ/SnakeBlock.cpp
	src/S2M/Objects/CNZ/TargetBumper.cpp
	src/S2M/Objects/CNZ/TriBumper.cpp
	src/S2M/Objects/CNZ/VFlipper.cpp
	src/S2M/Objects/Common/BGSwitch.cpp
	src/S2M/Objects/Common/BreakableWall.cpp
	src/S2M/Objects/Common/Button.cpp
	src/S2M/Objects/Common/CollapsingPlatform.cpp
	src/S2M/Objects/Common/Decoration.cpp
	src/S2M/Objects/Common/FallTrigger.cpp
	src/S2M/Objects/Common/FlingRamp.cpp
	src/S2M/Objects/Common/ForceSpin.cpp
	src/S2M/Objects/Common/ForceUnstick.cpp
	src/S2M/Objects/Common/GenericTrigger.cpp
	src/S2M/Objects/Common/ParallaxSprite.cpp
	src/S2M/Objects/Common/Platform.cpp
	src/S2M/Objects/Common/PlatformControl.cpp
	src/S2M/Objects/Common/PlatformNode.cpp
	src/S2M/Objects/Common/ScreenWrap.cpp
	src/S2M/Objects/Common/SpinBooster.cpp
	src/S2M/Objects/Common/Springboard.cpp
	src/S2M/Objects/Common/TilePlatform.cpp
	src/S2M/Objects/Common/Water.cpp
	src/S2M/Objects/CPZ/ChemicalBall.cpp
	src/S2M/Objects/CPZ/ChemicalDropper.cpp
	src/S2M/Objects/CPZ/CPZEggman.cpp
	src/S2M/Objects/CPZ/CPZSetup.cpp
	src/S2M/Objects/CPZ/Grabber.cpp
	src/S2M/Objects/CPZ/OneWayDoor.cpp
	src/S2M/Objects/CPZ/RotatingStair.cpp
	src/S2M/Objects/CPZ/SpeedBooster.cpp
	src/S2M/Objects/CPZ/Spiny.cpp
	src/S2M/Objects/CPZ/Staircase.cpp
	src/S2M/Objects/CPZ/TippingPlatform.cpp
	src/S2M/Objects/CPZ/TransportTube.cpp
	src/S2M/Objects/CPZ/TubeSpring.cpp
	src/S2M/Objects/DEZ/Blastoid.cpp
	src/S2M/Objects/DEZ/Crate.cpp
	src/S2M/Objects/DEZ/DEZSetup.cpp
	src/S2M/Objects/DEZ/FlasherMKII.cpp
	src/S2M/Objects/DEZ/JacobsLadder.cpp
	src/S2M/Objects/DEZ/MetalArm.cpp
	src/S2M/Objects/DEZ/PopOut.cpp
	src/S2M/Objects/DEZ/Press.cpp
	src/S2M/Objects/DEZ/Tubinaut.cpp
	src/S2M/Objects/EHZ/Bridge.cpp
	src/S2M/Objects/EHZ/BurningLog.cpp
	src/S2M/Objects/EHZ/Buzzer.cpp
	src/S2M/Objects/EHZ/Coconuts.cpp
	src/S2M/Objects/EHZ/CorkscrewPath.cpp
	src/S2M/Objects/EHZ/EggDriller.cpp
	src/S2M/Objects/EHZ/EHZEggman.cpp
	src/S2M/Objects/EHZ/EHZSetup.cpp
	src/S2M/Objects/EHZ/Masher.cpp
	src/S2M/Objects/Global/ActClear.cpp
	src/S2M/Objects/Global/Animals.cpp
	src/S2M/Objects/Global/Announcer.cpp
	src/S2M/Objects/Global/BoundsMarker.cpp
	src/S2M/Objects/Global/Camera.cpp
	src/S2M/Objects/Global/COverlay.cpp
	src/S2M/Objects/Global/Debris.cpp
	src/S2M/Objects/Global/DebugMode.cpp
	src/S2M/Objects/Global/Dust.cpp
	src/S2M/Objects/Global/EggPrison.cpp
	src/S2M/Objects/Global/Explosion.cpp
	src/S2M/Objects/Global/GameOver.cpp
	src/S2M/Objects/Global/HUD.cpp
	src/S2M/Objects/Global/ImageTrail.cpp
	src/S2M/Objects/Global/InvincibleStars.cpp
	src/S2M/Objects/Global/InvisibleBlock.cpp
	src/S2M/Objects/Global/ItemBox.cpp
	src/S2M/Objects/Global/Localization.cpp
	src/S2M/Objects/Global/Music.cpp
	src/S2M/Objects/Global/PauseMenu.cpp
	src/S2M/Objects/Global/PlaneSwitch.cpp
	src/S2M/Objects/Global/Player.cpp
	src/S2M/Objects/Global/ReplayRecorder.cpp
	src/S2M/Objects/Global/Ring.cpp
	src/S2M/Objects/Global/RPUpdate.cpp
	src/S2M/Objects/Global/SaveGame.cpp
	src/S2M/Objects/Global/ScoreBonus.cpp
	src/S2M/Objects/Global/Shield.cpp
	src/S2M/Objects/Global/SignPost.cpp
	src/S2M/Objects/Global/SpecialRing.cpp
	src/S2M/Objects/Global/Spikes.cpp
	src/S2M/Objects/Global/Spring.cpp
	src/S2M/Objects/Global/StarPost.cpp
	src/S2M/Objects/Global/SuperFlicky.cpp
	src/S2M/Objects/Global/SuperSparkle.cpp
	src/S2M/Objects/Global/TimeAttackGate.cpp
	src/S2M/Objects/Global/TitleCard.cpp
	src/S2M/Objects/Global/Zone.cpp
	src/S2M/Objects/Helpers/BadnikHelpers.cpp
	src/S2M/Objects/Helpers/CutsceneRules.cpp
	src/S2M/Objects/Helpers/CutsceneSeq.cpp
	src/S2M/Objects/Helpers/DialogRunner.cpp
	src/S2M/Objects/Helpers/DrawHelpers.cpp
	src/S2M/Objects/Helpers/FXAniTiles.cpp
	src/S2M/Objects/Helpers/FXAudioPan.cpp
	src/S2M/Objects/Helpers/FXFade.cpp
	src/S2M/Objects/Helpers/FXTileModifier.cpp
	src/S2M/Objects/Helpers/GameProgress.cpp
	src/S2M/Objects/Helpers/LogHelpers.cpp
	src/S2M/Objects/Helpers/MathHelpers.cpp
	src/S2M/Objects/Helpers/MenuParam.cpp
	src/S2M/Objects/Helpers/Options.cpp
	src/S2M/Objects/Helpers/PlayerHelpers.cpp
	src/S2M/Objects/Helpers/PlayerProbe.cpp
	src/S2M/Objects/Helpers/ReplayDB.cpp
	src/S2M/Objects/Helpers/RPCHelpers.cpp
	src/S2M/Objects/Helpers/Soundboard.cpp
	src/S2M/Objects/Helpers/TimeAttackData.cpp
	src/S2M/Objects/HPZ/Batbot.cpp
	src/S2M/Objects/HPZ/HPZSetup.cpp
	src/S2M/Objects/HPZ/Jellygnite.cpp
	src/S2M/Objects/HPZ/Pendulum.cpp
	src/S2M/Objects/HPZ/RailRocket.cpp
	src/S2M/Objects/HPZ/Redz.cpp
	src/S2M/Objects/HPZ/Stegway.cpp
	src/S2M/Objects/HPZ/WaterGush.cpp
	src/S2M/Objects/HTZ/AIZRockPile.cpp
	src/S2M/Objects/HTZ/HTZSetup.cpp
	src/S2M/Objects/HTZ/Rexon.cpp
	src/S2M/Objects/HTZ/RisingLava.cpp
	src/S2M/Objects/HTZ/SeeSaw.cpp
	src/S2M/Objects/HTZ/Sol.cpp
	src/S2M/Objects/HTZ/Spiker.cpp
	src/S2M/Objects/HTZ/ZipLine.cpp
	src/S2M/Objects/Menu/ContinuePlayer.cpp
	src/S2M/Objects/Menu/ContinueSetup.cpp
	src/S2M/Objects/Menu/DAControl.cpp
	src/S2M/Objects/Menu/DASetup.cpp
	src/S2M/Objects/Menu/ExtrasMenu.cpp
	src/S2M/Objects/Menu/LevelSelect.cpp
	src/S2M/Objects/Menu/MainMenu.cpp
	src/S2M/Objects/Menu/ManiaModeMenu.cpp
	src/S2M/Objects/Menu/MenuSetup.cpp
	src/S2M/Objects/Menu/OptionsMenu.cpp
	src/S2M/Objects/Menu/SaveMenu.cpp
	src/S2M/Objects/Menu/SaveMenuIconBG.cpp
	src/S2M/Objects/Menu/TAMenuIconBG.cpp
	src/S2M/Objects/Menu/ThanksSetup.cpp
	src/S2M/Objects/Menu/TimeAttackMenu.cpp
	src/S2M/Objects/Menu/UIButton.cpp
	src/S2M/Objects/Menu/UIButtonLabel.cpp
	src/S2M/Objects/Menu/UIButtonPrompt.cpp
	src/S2M/Objects/Menu/UICarousel.cpp
	src/S2M/Objects/Menu/UICharButton.cpp
	src/S2M/Objects/Menu/UIChoice.cpp
	src/S2M/Objects/Menu/UIControl.cpp
	src/S2M/Objects/Menu/UIDialog.cpp
	src/S2M/Objects/Menu/UIDiorama.cpp
	src/S2M/Objects/Menu/UIInfoLabel.cpp
	src/S2M/Objects/Menu/UIKeyBinder.cpp
	src/S2M/Objects/Menu/UILoadingIcon.cpp
	src/S2M/Objects/Menu/UIOptionPanel.cpp
	src/S2M/Objects/Menu/UIPicture.cpp
	src/S2M/Objects/Menu/UIPopover.cpp
	src/S2M/Objects/Menu/UIRankButton.cpp
	src/S2M/Objects/Menu/UIReplayCarousel.cpp
	src/S2M/Objects/Menu/UIResPicker.cpp
	src/S2M/Objects/Menu/UISaveSlot.cpp
	src/S2M/Objects/Menu/UIShifter.cpp
	src/S2M/Objects/Menu/UISlider.cpp
	src/S2M/Objects/Menu/UISubHeading.cpp
	src/S2M/Objects/Menu/UITABanner.cpp
	src/S2M/Objects/Menu/UITAZoneModule.cpp
	src/S2M/Objects/Menu/UIText.cpp
	src/S2M/Objects/Menu/UITransition.cpp
	src/S2M/Objects/Menu/UIVideo.cpp
	src/S2M/Objects/Menu/UIWidgets.cpp
	src/S2M/Objects/Menu/UIWinSize.cpp
	src/S2M/Objects/OOZ/Aquis.cpp
	src/S2M/Objects/OOZ/BallCannon.cpp
	src/S2M/Objects/OOZ/Fan.cpp
	src/S2M/Objects/OOZ/GasPlatform.cpp
	src/S2M/Objects/OOZ/Octus.cpp
	src/S2M/Objects/OOZ/OOZSetup.cpp
	src/S2M/Objects/OOZ/PushSpring.cpp
	src/S2M/Objects/SFZ/SCZSetup.cpp
	src/S2M/Objects/SFZ/Tornado.cpp
	src/S2M/Objects/SFZ/TornadoPath.cpp
	src/S2M/Objects/Special/HP_Background.cpp
	src/S2M/Objects/Special/HP_Checkpoint.cpp
	src/S2M/Objects/Special/HP_Collectable.cpp
	src/S2M/Objects/Special/HP_Halfpipe.cpp
	src/S2M/Objects/Special/HP_HUD.cpp
	src/S2M/Objects/Special/HP_Message.cpp
	src/S2M/Objects/Special/HP_Player.cpp
	src/S2M/Objects/Special/HP_Setup.cpp
	src/S2M/Objects/Special/HP_SpecialClear.cpp
	src/S2M/Objects/SSZ/Bomb.cpp
	src/S2M/Objects/SSZ/Caterkiller.cpp
	src/S2M/Objects/SSZ/Pinata.cpp
	src/S2M/Objects/SSZ/RollerMKII.cpp
	src/S2M/Objects/SSZ/SeltzerBottle.cpp
	src/S2M/Objects/SSZ/SeltzerWater.cpp
	src/S2M/Objects/SSZ/SinkTrash.cpp
	src/S2M/Objects/SSZ/SSZSetup.cpp
	src/S2M/Objects/SSZ/Vultron.cpp
	src/S2M/Objects/SWZ/BouncePlant.cpp
	src/S2M/Objects/SWZ/Dragonfly.cpp
	src/S2M/Objects/SWZ/GymBar.cpp
	src/S2M/Objects/SWZ/PetalPile.cpp
	src/S2M/Objects/SWZ/Rhinobot.cpp
	src/S2M/Objects/SWZ/Snowflakes.cpp
	src/S2M/Objects/SWZ/Splats.cpp
	src/S2M/Objects/SWZ/SWZSetup.cpp
	src/S2M/Objects/SWZ/UncurlPlant.cpp
	src/S2M/Objects/SWZ/WallBumper.cpp
	src/S2M/Objects/Test/TestObject.cpp
	src/S2M/Objects/Title/LogoSetup.cpp
	src/S2M/Objects/Title/Sega.cpp
	src/S2M/Objects/Title/TitleLogo.cpp
	src/S2M/Objects/Title/TitleSetup.cpp
	src/S2M/Objects/Title/TitleSonic.cpp
	src/S2M/Objects/Title/Twinkle.cpp
)